# Generated by Django 2.2.6 on 2019-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('rank', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('add_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('rank', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=10)),
            ],
        ),
    ]
