# Generated by Django 2.2.6 on 2019-10-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0003_itemcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itemcontent',
        ),
    ]
