# Generated by Django 2.2.6 on 2019-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
