# Generated by Django 2.2.6 on 2019-11-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0007_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, upload_to='mobiles'),
        ),
    ]
