# Generated by Django 2.2.6 on 2019-11-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0009_auto_20191102_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, upload_to='mobiles'),
        ),
    ]
