# Generated by Django 2.2.6 on 2019-11-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0012_auto_20191103_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='name',
        ),
    ]
