# Generated by Django 2.2.6 on 2019-11-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0013_auto_20191103_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='title',
        ),
    ]
