# Generated by Django 2.2.6 on 2019-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopin', '0015_auto_20191103_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
